// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvqyhftgqonejozdefaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2cXloZnRncW9uZWpvemRlZmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDE5ODMsImV4cCI6MjA2NzIxNzk4M30.jVXBI8e65fz-7qwCs5nOxzqg_lfSznUkilvtA5i0i0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});